# Generated by Django 3.1 on 2020-09-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.CharField(default='0$', max_length=500),
        ),
        migrations.AddField(
            model_name='listings',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
