# Generated by Django 3.1 on 2020-09-30 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200930_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.CharField(default='$0', max_length=500),
        ),
        migrations.AlterField(
            model_name='listings',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
