# Generated by Django 3.1 on 2020-09-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200930_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
