# Generated by Django 3.1 on 2020-10-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='decription',
            new_name='description',
        ),
    ]
