# Generated by Django 3.1 on 2020-10-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.CharField(max_length=64)),
                ('bid', models.IntegerField()),
                ('listid', models.IntegerField()),
            ],
        ),
    ]
