# Generated by Django 3.1 on 2020-10-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_wathlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wathlist',
            new_name='Watchlist',
        ),
    ]
