# Generated by Django 3.1 on 2020-10-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201004_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
