# Generated by Django 3.1 on 2020-10-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_closedbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedbid',
            name='winprice',
            field=models.CharField(max_length=5000000000000000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(default='$0', max_length=5000000000000000),
        ),
    ]
