# Generated by Django 3.1 on 2020-10-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201005_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField()),
                ('dateclosed', models.DateTimeField()),
                ('owner', models.CharField(max_length=64)),
                ('winner', models.CharField(max_length=64)),
                ('winprice', models.CharField(max_length=5000000000000000)),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ClosedBid',
        ),
    ]
