# Generated by Django 3.1 on 2020-10-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201005_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedlisting',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
