# Generated by Django 3.1 on 2020-10-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201005_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedlisting',
            name='listid',
            field=models.CharField(blank=True, max_length=500000000000000, null=True),
        ),
    ]
